// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function AddProjectDir(arg1:string):Promise<void>;

export function ApplyUpdate(arg1:string):Promise<string>;

export function BackupToProvider(arg1:string,arg2:string):Promise<void>;

export function BackupToWebDAV(arg1:string):Promise<void>;

export function CancelDownload():Promise<void>;

export function CheckForUpdates():Promise<string>;

export function ClearLogs():Promise<void>;

export function DeleteArchive(arg1:string):Promise<string>;

export function DeleteBackups(arg1:string,arg2:Array<string>):Promise<void>;

export function DeleteCodexSession(arg1:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function DeleteWebDAVBackups(arg1:Array<string>):Promise<void>;

export function DetectBackupConflict(arg1:string,arg2:string):Promise<string>;

export function DetectTerminals():Promise<string>;

export function DetectWebDAVConflict(arg1:string):Promise<string>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<void>;

export function FetchBroadcast(arg1:string):Promise<string>;

export function FetchImageAsBase64(arg1:string):Promise<string>;

export function FetchModels(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateMockArchives(arg1:number):Promise<string>;

export function GetArchiveData(arg1:string):Promise<string>;

export function GetArchiveTrend(arg1:string):Promise<string>;

export function GetAutoDarkTheme():Promise<string>;

export function GetAutoLightTheme():Promise<string>;

export function GetChangelog(arg1:string):Promise<string>;

export function GetCodexSessionData(arg1:string):Promise<string>;

export function GetCodexSessions(arg1:string):Promise<string>;

export function GetConfig():Promise<string>;

export function GetCurrentEndpoint():Promise<string>;

export function GetDownloadProgress():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLogLevel():Promise<number>;

export function GetLogs():Promise<string>;

export function GetLogsByLevel(arg1:number):Promise<string>;

export function GetProxyURL():Promise<string>;

export function GetSessionData(arg1:string,arg2:string):Promise<string>;

export function GetSessions(arg1:string):Promise<string>;

export function GetStats():Promise<string>;

export function GetStatsDaily():Promise<string>;

export function GetStatsMonthly():Promise<string>;

export function GetStatsTrend():Promise<string>;

export function GetStatsTrendByPeriod(arg1:string):Promise<string>;

export function GetStatsWeekly():Promise<string>;

export function GetStatsYesterday():Promise<string>;

export function GetSystemLanguage():Promise<string>;

export function GetTerminalConfig():Promise<string>;

export function GetTheme():Promise<string>;

export function GetThemeAuto():Promise<boolean>;

export function GetUpdateSettings():Promise<string>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function InstallUpdate(arg1:string):Promise<string>;

export function LaunchCodexSessionTerminal(arg1:string,arg2:string):Promise<void>;

export function LaunchCodexTerminal(arg1:string):Promise<void>;

export function LaunchSessionTerminal(arg1:string,arg2:string):Promise<void>;

export function LaunchTerminal(arg1:string):Promise<void>;

export function ListArchives():Promise<string>;

export function ListBackups(arg1:string):Promise<string>;

export function ListWebDAVBackups():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RemoveEndpoint(arg1:number):Promise<void>;

export function RemoveProjectDir(arg1:string):Promise<void>;

export function RenameCodexSession(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderEndpoints(arg1:Array<string>):Promise<void>;

export function RestoreFromProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreFromWebDAV(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SaveTerminalConfig(arg1:string,arg2:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendUpdateNotification(arg1:string,arg2:string):Promise<void>;

export function SetAutoDarkTheme(arg1:string):Promise<void>;

export function SetAutoLightTheme(arg1:string):Promise<void>;

export function SetCloseWindowBehavior(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLogLevel(arg1:number):Promise<void>;

export function SetProxyURL(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetThemeAuto(arg1:boolean):Promise<void>;

export function SetUpdateSettings(arg1:boolean,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function SwitchToEndpoint(arg1:string):Promise<void>;

export function TestAllEndpointsZeroCost():Promise<string>;

export function TestEndpoint(arg1:number):Promise<string>;

export function TestEndpointLight(arg1:number):Promise<string>;

export function TestS3Connection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<string>;

export function TestWebDAVConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleEndpoint(arg1:number,arg2:boolean):Promise<void>;

export function UpdateBackupProvider(arg1:string):Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;

export function UpdateEndpoint(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function UpdateLocalBackupDir(arg1:string):Promise<void>;

export function UpdateNetwork(arg1:number,arg2:string):Promise<void>;

export function UpdatePort(arg1:number):Promise<void>;

export function UpdateS3BackupConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<void>;

export function UpdateWebDAVConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
