// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddProjectDir(arg1) {
  return window['go']['main']['App']['AddProjectDir'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function BackupToProvider(arg1, arg2) {
  return window['go']['main']['App']['BackupToProvider'](arg1, arg2);
}

export function BackupToWebDAV(arg1) {
  return window['go']['main']['App']['BackupToWebDAV'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteArchive(arg1) {
  return window['go']['main']['App']['DeleteArchive'](arg1);
}

export function DeleteBackups(arg1, arg2) {
  return window['go']['main']['App']['DeleteBackups'](arg1, arg2);
}

export function DeleteCodexSession(arg1) {
  return window['go']['main']['App']['DeleteCodexSession'](arg1);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DeleteWebDAVBackups(arg1) {
  return window['go']['main']['App']['DeleteWebDAVBackups'](arg1);
}

export function DetectBackupConflict(arg1, arg2) {
  return window['go']['main']['App']['DetectBackupConflict'](arg1, arg2);
}

export function DetectTerminals() {
  return window['go']['main']['App']['DetectTerminals']();
}

export function DetectWebDAVConflict(arg1) {
  return window['go']['main']['App']['DetectWebDAVConflict'](arg1);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function FetchBroadcast(arg1) {
  return window['go']['main']['App']['FetchBroadcast'](arg1);
}

export function FetchImageAsBase64(arg1) {
  return window['go']['main']['App']['FetchImageAsBase64'](arg1);
}

export function FetchModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2, arg3);
}

export function GenerateMockArchives(arg1) {
  return window['go']['main']['App']['GenerateMockArchives'](arg1);
}

export function GetArchiveData(arg1) {
  return window['go']['main']['App']['GetArchiveData'](arg1);
}

export function GetArchiveTrend(arg1) {
  return window['go']['main']['App']['GetArchiveTrend'](arg1);
}

export function GetAutoDarkTheme() {
  return window['go']['main']['App']['GetAutoDarkTheme']();
}

export function GetAutoLightTheme() {
  return window['go']['main']['App']['GetAutoLightTheme']();
}

export function GetChangelog(arg1) {
  return window['go']['main']['App']['GetChangelog'](arg1);
}

export function GetCodexSessionData(arg1) {
  return window['go']['main']['App']['GetCodexSessionData'](arg1);
}

export function GetCodexSessions(arg1) {
  return window['go']['main']['App']['GetCodexSessions'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentEndpoint() {
  return window['go']['main']['App']['GetCurrentEndpoint']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsByLevel(arg1) {
  return window['go']['main']['App']['GetLogsByLevel'](arg1);
}

export function GetProxyURL() {
  return window['go']['main']['App']['GetProxyURL']();
}

export function GetSessionData(arg1, arg2) {
  return window['go']['main']['App']['GetSessionData'](arg1, arg2);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatsDaily() {
  return window['go']['main']['App']['GetStatsDaily']();
}

export function GetStatsMonthly() {
  return window['go']['main']['App']['GetStatsMonthly']();
}

export function GetStatsTrend() {
  return window['go']['main']['App']['GetStatsTrend']();
}

export function GetStatsTrendByPeriod(arg1) {
  return window['go']['main']['App']['GetStatsTrendByPeriod'](arg1);
}

export function GetStatsWeekly() {
  return window['go']['main']['App']['GetStatsWeekly']();
}

export function GetStatsYesterday() {
  return window['go']['main']['App']['GetStatsYesterday']();
}

export function GetSystemLanguage() {
  return window['go']['main']['App']['GetSystemLanguage']();
}

export function GetTerminalConfig() {
  return window['go']['main']['App']['GetTerminalConfig']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetThemeAuto() {
  return window['go']['main']['App']['GetThemeAuto']();
}

export function GetUpdateSettings() {
  return window['go']['main']['App']['GetUpdateSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function LaunchCodexSessionTerminal(arg1, arg2) {
  return window['go']['main']['App']['LaunchCodexSessionTerminal'](arg1, arg2);
}

export function LaunchCodexTerminal(arg1) {
  return window['go']['main']['App']['LaunchCodexTerminal'](arg1);
}

export function LaunchSessionTerminal(arg1, arg2) {
  return window['go']['main']['App']['LaunchSessionTerminal'](arg1, arg2);
}

export function LaunchTerminal(arg1) {
  return window['go']['main']['App']['LaunchTerminal'](arg1);
}

export function ListArchives() {
  return window['go']['main']['App']['ListArchives']();
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListWebDAVBackups() {
  return window['go']['main']['App']['ListWebDAVBackups']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveEndpoint(arg1) {
  return window['go']['main']['App']['RemoveEndpoint'](arg1);
}

export function RemoveProjectDir(arg1) {
  return window['go']['main']['App']['RemoveProjectDir'](arg1);
}

export function RenameCodexSession(arg1, arg2) {
  return window['go']['main']['App']['RenameCodexSession'](arg1, arg2);
}

export function RenameSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2, arg3);
}

export function ReorderEndpoints(arg1) {
  return window['go']['main']['App']['ReorderEndpoints'](arg1);
}

export function RestoreFromProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreFromProvider'](arg1, arg2, arg3);
}

export function RestoreFromWebDAV(arg1, arg2) {
  return window['go']['main']['App']['RestoreFromWebDAV'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTerminalConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveTerminalConfig'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendUpdateNotification(arg1, arg2) {
  return window['go']['main']['App']['SendUpdateNotification'](arg1, arg2);
}

export function SetAutoDarkTheme(arg1) {
  return window['go']['main']['App']['SetAutoDarkTheme'](arg1);
}

export function SetAutoLightTheme(arg1) {
  return window['go']['main']['App']['SetAutoLightTheme'](arg1);
}

export function SetCloseWindowBehavior(arg1) {
  return window['go']['main']['App']['SetCloseWindowBehavior'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function SetProxyURL(arg1) {
  return window['go']['main']['App']['SetProxyURL'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetThemeAuto(arg1) {
  return window['go']['main']['App']['SetThemeAuto'](arg1);
}

export function SetUpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['SetUpdateSettings'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SkipVersion(arg1) {
  return window['go']['main']['App']['SkipVersion'](arg1);
}

export function SwitchToEndpoint(arg1) {
  return window['go']['main']['App']['SwitchToEndpoint'](arg1);
}

export function TestAllEndpointsZeroCost() {
  return window['go']['main']['App']['TestAllEndpointsZeroCost']();
}

export function TestEndpoint(arg1) {
  return window['go']['main']['App']['TestEndpoint'](arg1);
}

export function TestEndpointLight(arg1) {
  return window['go']['main']['App']['TestEndpointLight'](arg1);
}

export function TestS3Connection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['TestS3Connection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function TestWebDAVConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebDAVConnection'](arg1, arg2, arg3);
}

export function ToggleEndpoint(arg1, arg2) {
  return window['go']['main']['App']['ToggleEndpoint'](arg1, arg2);
}

export function UpdateBackupProvider(arg1) {
  return window['go']['main']['App']['UpdateBackupProvider'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateEndpoint(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateLocalBackupDir(arg1) {
  return window['go']['main']['App']['UpdateLocalBackupDir'](arg1);
}

export function UpdateNetwork(arg1, arg2) {
	return window['go']['main']['App']['UpdateNetwork'](arg1, arg2);
}

export function UpdatePort(arg1) {
  return window['go']['main']['App']['UpdatePort'](arg1);
}

export function UpdateS3BackupConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateS3BackupConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateWebDAVConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWebDAVConfig'](arg1, arg2, arg3);
}
